<Project Sdk="MSTest.Sdk/3.6.4">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../GridPool.DashboardSimulator/GridPool.DashboardSimulator.csproj" />
  </ItemGroup>
</Project>
