import type { DashboardSummary } from "../types";

export const summaryFixture: DashboardSummary = {
  schemaVersion: 1,
  revision: 1,
  generatedAtUtc: "2026-07-29T12:00:00Z",
  node: {
    nodeId: "node-id",
    displayName: "Test node",
    region: "Lab",
    role: "test",
    publicEndpoint: "https://test.gridpool.net",
    networkId: "testnet4-beta",
    bitcoinNetwork: "testnet4",
    releaseVersion: "1.1.0-beta",
    consensusVersion: 22,
    protocolVersion: 22,
    httpApiVersion: 1,
    serviceStartedUtc: "2026-07-29T10:00:00Z"
  },
  health: {
    status: "ready",
    miningWorkSafe: true,
    miningWorkSafetyReason: "",
    peerCount: 4,
    peerLoopsHealthy: true,
    outboundRelayHealthy: true,
    bitcoinNotificationMode: "attached-node",
    bitcoinAuthorityClass: "locally-validated",
    bitcoinRpcReachable: true,
    bitcoinRpcSynced: true,
    bitcoinInitialBlockDownload: false,
    currentTipBlockHash: "0000000000000000000000000000000000000000000000000000000000000001",
    currentTipBlockHeight: 123,
    provisionalTipBlockHash: "",
    lastPeerPollCompletedUtc: "2026-07-29T11:59:59Z"
  },
  snapshot: {
    roundNumber: 9,
    currentStateId: "current",
    candidateStateId: "candidate",
    activeSnapshotId: "snapshot",
    activeSnapshotFamilyId: "family",
    lockedPayoutCount: 299,
    lockedProofCount: 299,
    reserveCount: 897,
    reserveLimit: 897,
    reserveFloorDifficulty: 100,
    reserveFloorDifficultyDisplay: "100",
    lastRotationUtc: "2026-07-29T11:00:00Z",
    familyMemberCount: 1,
    familyUnionProofCount: 897,
    reconciliation: {}
  },
  workRate: {
    window: "24h",
    windowSeconds: 86400,
    windowStartUtc: "2026-07-28T12:00:00Z",
    windowEndUtc: "2026-07-29T12:00:00Z",
    observationCount: 897,
    retainedOrderStatisticCount: 897,
    estimateThs: 1000,
    estimateDisplay: "1 PH/s",
    orderStatisticDifficulty: 100,
    orderStatisticDifficultyDisplay: "100",
    effectiveAdmissionFloorDifficulty: 1,
    effectiveAdmissionFloorDisplay: "1",
    relativeStandardErrorPercent: 3.34,
    confidence: "high",
    warmup: false,
    completeWindow: true,
    method: "difficulty-order-statistic",
    note: "Complete window."
  },
  pulse: {
    enabled: true,
    acceptedTotal: 12,
    acceptedInWindow: 4,
    acceptedPerMinute: 0.1,
    lastAcceptedUtc: "2026-07-29T11:59:00Z",
    lastSuccessfulOutboundRelayUtc: "2026-07-29T11:59:01Z",
    outboundRelayHealthy: true,
    targetIntervalSeconds: 60,
    relayTtl: 1,
    interpretation: "Pulse proofs are liveness."
  },
  capabilities: {
    webUiEnabled: true,
    legacyUiEnabled: true,
    operatorApiAvailable: true,
    addressLookupAvailable: true,
    workRateTelemetryAvailable: true,
    pulseTelemetryAvailable: true,
    watchtowerAvailable: false,
    modules: []
  }
};
